### ISSUE TITLE
reduce false positives in uptime-check

### ISSUE THREAD

**Issue by afeld** [18F/concourse-compliance-testing#11]
Currently, that task reports "No `links`" for a number of projects that we want to ignore:

```
No `links` for about_yml.
No `links` for authdelegate.
No `links` for 18f-identity.
No `links` for dodsbir-scrape.
No `links` for fec-cms.
No `links` for fec-style.
No `links` for hmacauth.
No `links` for laptop.
No `links` for openFEC-web-app.
No `links` for SBIR-EZ.
No `links` for sbirez.
No `links` for team_api.
No `links` for uscis.
https://team-browser.18f.gov/ is NOT up.
https://18f.gsa.gov/team-browser/ is NOT up.
https://www.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks%40group.calendar.google.com&ctz=America/Los_Angeles is NOT up.
https://team-browser.18f.gov/team-browser/ is NOT up.
```

Issues identified in that list:
- [`SBIR-EZ` is a defunct project.](https://18f.slack.com/archives/cloud-gov-support/p1457465156001035)
  - Is there a good way to indicate this in the about.yml?
- `about_yml` and `laptop` don't have standalone sites—should `links` include a reference to the repository? We might want to say explicitly one way or another in the about.yml instructions.

Ideas for improvement:
- [ ] Reach out to projects/teams where the about.yml seems out-of-date
- [ ] Filter by `status`
  - I see this in some of the entries in [`/projects`](https://team-api.18f.gov/public/api/projects/), but it's not listed in the instructions.
- [ ] Filter by ____?
  - My initial thinking was "oh, there's just some field

Resources:
- https://github.com/18F/about_yml/blob/master/template.yml
- https://github.com/18F/about_yml/#cheat-sheet

@mtorres253 @ertzeid @ccostino The background here is that I'm pulling a list of URLs from the `links` provided in the Projects list of the Team API, for automatically checking if the sites are up, doing security scans, etc. Any advice on how to do better filtering of that list?

**Comment by mtorres253** [comment]
Hi @afeld! The `links` field should be for URLs (like a website for a project, or the website of the parent repo, etc). The github repo should be derived automatically (if the project has its own repo) and available via the Team API (`github`).  The status field is no longer in the schema, but we may want to add back. Sounds like you need:
1. Updated about.yml for those projects that have a website URL (so that you can monitor uptime, security, etc)
2. A flag to indicate whether a project is active or inactive (defunct or for some other reason - team browser is still in development and is in pre-release status, for example) so that you can look at active projects only
3. The github repo of each project (available for projects with repos in the`github` attribute)

I can't think of another filter that would give you the status of a particular project. @ertzeid - any ideas?

**Comment by afeld** [comment]
> The github repo should be derived automatically

Ah sorry, hadn't seen the `github` field!

> A flag to indicate whether a project is active or inactive...so that you can look at active projects only

We're going to make these scans opt-in for now on our side, so not urgent, but I could see such a status indicator being useful, yes. Maybe `status` and `stage` can be consolidated?

**Comment by afeld** [comment]
@melodykramer You had done some thinking about the "stages" of projects, right?

**Comment by mtorres253** [comment]
Yes, @afeld, we did some research into stages of a project, but we never landed on anything particularly useful IMO. The status of active/inactive could be derived from the stage - the stage could simply have a value of alpha, beta, live or inactive (it might be overloaded but until we have more info, this may be the easiest thing to do.) I believe the dashboard/18F site team will do more research to flesh that out @melodykramer

**Comment by afeld** [comment]
https://trello.com/c/ZagzVLuH/107-limit-links-scanned-by-zap-to-gov-domains will help, too.

**Comment by afeld** [comment]
Closing, since we have made more specific Trello cards and now have workarounds for most of these issues.
